name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.0
  shared_preferences: ^2.0.0
  

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
   # Adicione ou altere para 23

  assets:
  - assets/games.csv
  - assets/dataset_filtrado.csv
  